### ISSUE TITLE
wrong declaration name module in index.d.ts

### ISSUE THREAD

**Issue by retr0mon** [mikbry/mui-color#1]
Hello, thank you for this project and the migration to mui v5. 

I use TypeScript and I have the following errors:

`File '/home/.../node_modules/mui-color/index.d.ts' is not a module.`

In file mui-color/src/types/index.d.ts

Solution :
// change this
`declare module 'material-ui-color'`
// to this
`declare module 'mui-color'`

thank you

**Comment by ivan-romanchuk-axon** [comment]
@mikbry Could you please create a new tag which will contain merged fix?

**Comment by mikbry** [comment]
I just released mui-color@2.0.0-beta.2

**Comment by ivan-romanchuk-axon** [comment]
@mikbry thank you so much. Could you also update peer dependency to support **material-ui-popup-state ^2.0.0 (now ^1.5.3)** (mui v5 is supported since this version). If you need, I can create a separate issue for this request.

**Comment by mikbry** [comment]
@ivan-romanchuk-axon thanks, yes create another issue for this dependency
